### ISSUE TITLE
Releasing monai label v0.5.2 -- Checklist

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/MONAILabel#1067]
Releasing activities for MONAI Label v0.5.2:

Environments and Basic Tests
- [x] Upgrade dependency with MONAI v1.0.1 rc1 version, pip install monai==1.0.1rc1, locally.
- [x] First Step: upgrade monai to 1.0.1rc1 PR
- [x] Unit Test and Integration pass. Unit and Integration tests passed locally by running ./runtests.sh --net ./runtests.sh -u

Assurance for functionalities: 

GPU tests:
- [x]  Verify Radiology App for all models (infer, train on single/multi-gpu)
- [x]  Verify Pathology App for all models (infer, train on single/multi-gpu)
- [x]  Verify Endscopy App for all models (infer, train on single/multi-gpu)
- [x]  Verify Bundle App for all models (infer, train on single/multi-gpu)

Client Verification:
- [x]  Verify client 3D Slicer, new UI, options
- [x]  Verify client OHIF (next sample, infer, train)
- [x]  Verify client QuPath
- [x]  Verify client DSA
- [x]  Verify DicomWeb Server support (Orthanic)
- [x]  Scribbles (OHIF + 3D Slicer) (best works in 3D Slicer due to ROI)

Verify Docker, 
- [x] Once verified Docker, Verify the CVAT+Nuclio, function containers

Prepare and Verify Documentations
- [x]  Verify all documents
- [x]  Draft a release note on GitHub. (including details about the breaking, deprecated changes)
- [x]  Check all the URLs in https://docs.monai.io/, especially MONAI Label Docs
- [x]  Check all the URLs in GitHub docs, readmes, (https://github.com/project-monai/monailabel)
- [ ]  Draft a release note with a pull request to modify the CHANGELOG.

Release hotfix version
- [x] Tag and release PyPI version [X.Y.Z] following the contributing guide.
- [x] Publish the release note on GitHub.

**Comment by diazandr3s** [comment]
I love this list. We can use this as a reference for future releases. Thanks, @tangy5

**Comment by tangy5** [comment]
First step: 
Unit, integration test passed locally with monai==1.0.1rc1, 
Basic runs with sample apps infer/train with GPUs passed
PR: https://github.com/Project-MONAI/MONAILabel/issues/1067

TODO: 

- [ ] We need a Endoscopy app integration test. 
- [ ] Check and update all documentation to match 0.5.2
